## https://taplo.tamasfe.dev/configuration/file.html

include = ["*.toml", ".cargo/*.toml", ".config/*.toml", "packages/**/*.toml"]
exclude = ["**/node_modules"]

[formatting]
align_entries = false
array_trailing_comma = true
array_auto_expand = true
array_auto_collapse = false
compact_arrays = true
compact_inline_tables = false
column_width = 100
indent_tables = false
indent_string = '    '
trailing_newline = true
reorder_keys = false
allowed_blank_lines = 1
crlf = false

[[rule]]
keys = ["build-dependencies", "dependencies", "dev-dependencies", "workspace.dependencies"]
formatting = { reorder_keys = true }

[[rule]]
keys = ["package"]
formatting = { reorder_keys = false }
